FROM ubuntu:latest

ARG PROJECT_DIR="/homepage"
ARG GEM_DIR="/gem"

RUN apt-get update
RUN apt-get upgrade --yes
RUN apt-get install --yes ruby-full build-essential zlib1g-dev git
RUN gem install jekyll -v 3.8.6 
RUN gem install bundler -v 2.1.2
RUN gem update --system

COPY Gemfile $GEM_DIR/
COPY minima.gemspec $GEM_DIR/
WORKDIR $GEM_DIR
RUN bundle config set path "${GEM_DIR}/vendor"
RUN bundle install

RUN mkdir $PROJECT_DIR
WORKDIR $PROJECT_DIR
ADD . $PROJECT_DIR
RUN bundle update

EXPOSE 35729
EXPOSE 4000
CMD ["sh", "-c", "cp /gem/Gemfile.lock /homepage/ && jekyll serve --force_polling --livereload --host 0.0.0.0"]
